[package]
name = "rere"
version = "0.1.0"
edition = "2021"

[dependencies]
bi-parser = { path = "../bi-parser" }
clap = { version = "4.5.8", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
